### ISSUE TITLE
addTrip function in Station

### ISSUE THREAD

**Issue by mduboef** [RPI-Subway-Challenge/subwayChallenge#17]

**Comment by MattLMerritt** [comment]
Added createStationsTrips function in algo.cpp for creating trips between stations using the walkableNumber function. Completed the addtrip function but with functionality to add trips for all stations.
@SHA: 355bde6cc4c38e4611950a68de2ebae51230ccb9

**Comment by MattLMerritt** [comment]
Added createStationsTrips function in algo.cpp for creating trips between stations using the walkableNumber function. Completed the addtrip function but with functionality to add trips for all stations.
SHA: 355bde6cc4c38e4611950a68de2ebae51230ccb9
